### ISSUE TITLE
async entities???

### ISSUE THREAD

**Issue by DivannKokos** [FIGRJA/combo_auth#3]
```
[04:29:49] [User Authenticator #2/ERROR] (class_3248) Couldn't place player in world
java.util.ConcurrentModificationException: Async entity load
        at net.minecraft.class_3898.handler$zdo000$c2me-fixes-general-threading-issues$preventAsyncEntityLoad(class_3898.java:5426) ~[server-intermediary.jar:?]
        at net.minecraft.class_3898.method_18701(class_3898.java) ~[server-intermediary.jar:?]
        at net.minecraft.class_3215.method_18755(class_3215.java:484) ~[server-intermediary.jar:?]
        at net.minecraft.class_3218$class_5526.method_31436(class_3218.java:1558) ~[server-intermediary.jar:?]
        at net.minecraft.class_3218$class_5526.method_31798(class_3218.java:1536) ~[server-intermediary.jar:?]
        at net.minecraft.class_5579.method_31847(class_5579.java:216) ~[server-intermediary.jar:?]
        at net.minecraft.class_5579.method_31820(class_5579.java:186) ~[server-intermediary.jar:?]
        at net.minecraft.class_5579.method_31818(class_5579.java:167) ~[server-intermediary.jar:?]
        at net.minecraft.class_3218.method_18771(class_3218.java:902) ~[server-intermediary.jar:?]
        at net.minecraft.class_3218.method_18213(class_3218.java:888) ~[server-intermediary.jar:?]
        at net.minecraft.class_3324.method_14570(class_3324.java:261) ~[server-intermediary.jar:?]
        at net.minecraft.class_3248.method_33800(class_3248.java:131) ~[server-intermediary.jar:?]
        at net.minecraft.class_3248.method_14384(class_3248.java:118) ~[server-intermediary.jar:?]
        at net.minecraft.class_3248.handler$zko000$combo_auth$init(class_3248.java:579) ~[server-intermediary.jar:?]
        at net.minecraft.class_3248.method_14380(class_3248.java) ~[server-intermediary.jar:?]
        at net.minecraft.class_3248$1.run(class_3248.java:210) ~[server-intermediary.jar:?]
```

c2me dev about another mod wrote that they won't disable checks for async entities
so, i think if combo auth is listed here, somehow your mod use async entity??? i don't know about modding, either way this happens for 1 of 3 players for me, and it is bad

**Comment by DivannKokos** [comment]
https://github.com/RelativityMC/C2ME-fabric/issues/278 about another mod

**Comment by FIGRJA** [comment]
fixed in new version.(1.3)
