### ISSUE TITLE
One of my ely friends can't join on my server with this mod.

### ISSUE THREAD

**Issue by ghost** [FIGRJA/combo_auth#5]
[07:24:17] [User Authenticator #3/ERROR]: Caught previously unhandled exception :
java.lang.NullPointerException: Cannot invoke "org.figrja.combo_auth.ely.by.resultElyGson.getProperties()" because "pr" is null
        at org.figrja.combo_auth.ely.by.auth_api.hasJoinedServer(auth_api.java:43) ~[combo_auth-1.1.1-1.20.2.jar:?]
        at net.minecraft.class_3248.handler$zdk000$combo_auth$init(class_3248.java:570) ~[server-intermediary.jar:?]
        at net.minecraft.class_3248.method_14380(class_3248.java) ~[server-intermediary.jar:?]
        at net.minecraft.class_3248$1.run(class_3248.java:212) ~[server-intermediary.jar:?]
[07:24:46] [Server thread/INFO]: reina_here lost connection: Took too long to log in
[07:24:46] [Server thread/WARN]: handleDisconnection() called twice

**Comment by FIGRJA** [comment]
I didn't think about the default skin, which returns nothing

**Comment by TechnoSparks** [comment]
I faced the same error. Thank you for mentioning default skin.

That means for anyone who came across this issue, the **workaround** is to make sure the ely.by account holder set a skin prior to joining.

**Comment by FIGRJA** [comment]
fixed in new version. Maybe...
