### ISSUE TITLE
Failed to verify Services signature

### ISSUE THREAD

**Issue by alexsovi** [FIGRJA/combo_auth#7]
When my friend joins my server with Ely.by on 1.21, he gets that error.
Here's the part of log from server:
[11:18:39] [Server thread/INFO]: sqsqd118[/37.212.90.9:24832] logged in with entity id 312 at (74.5, 72.0, -54.5)
[11:18:39] [Server thread/INFO]: sqsqd118 joined the game
[11:18:39] [Server thread/INFO]: Async chunk loading for player sqsqd118 completed
[11:18:39] [Server thread/ERROR]: Failed to verify Services signature
java.security.SignatureException: Bad signature length: got 1 but was expecting 512
        at java.base/sun.security.rsa.RSASignature.engineVerify(RSASignature.java:212) ~[?:?]
        at java.base/java.security.Signature$Delegate.engineVerify(Signature.java:1422) ~[?:?]
        at java.base/java.security.Signature.verify(Signature.java:790) ~[?:?]
        at MC/net.minecraft.network.encryption.SignatureVerifier.verify(SignatureVerifier.java:28) ~[server-intermediary.jar:?]
        at MC/net.minecraft.network.encryption.SignatureVerifier.method_44173(SignatureVerifier.java:53) ~[server-intermediary.jar:?]
        at java.base/java.util.stream.MatchOps$1MatchSink.accept(MatchOps.java:90) ~[?:?]
        at java.base/java.util.AbstractList$RandomAccessSpliterator.tryAdvance(AbstractList.java:708) ~[?:?]
        at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129) ~[?:?]
        at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:527) ~[?:?]
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:513) ~[?:?]
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
        at java.base/java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230) ~[?:?]
        at java.base/java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:196) ~[?:?]
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
        at java.base/java.util.stream.ReferencePipeline.anyMatch(ReferencePipeline.java:632) ~[?:?]
        at MC/net.minecraft.network.encryption.SignatureVerifier.method_51496(SignatureVerifier.java:50) ~[server-intermediary.jar:?]
        at MC/net.minecraft.network.encryption.SignatureVerifier.validate(SignatureVerifier.java:23) ~[server-intermediary.jar:?]
        at MC/net.minecraft.network.encryption.PlayerPublicKey$PublicKeyData.verifyKey(PlayerPublicKey.java:74) ~[server-intermediary.jar:?]
        at MC/net.minecraft.network.encryption.PlayerPublicKey.verifyAndDecode(PlayerPublicKey.java:30) ~[server-intermediary.jar:?]
        at MC/net.minecraft.network.encryption.PublicPlayerSession$Serialized.toSession(PublicPlayerSession.java:42) ~[server-intermediary.jar:?]
        at MC/net.minecraft.server.network.ServerPlayNetworkHandler.onPlayerSession(ServerPlayNetworkHandler.java:1889) ~[server-intermediary.jar:?]
        at MC/net.minecraft.network.packet.c2s.play.PlayerSessionC2SPacket.apply(PlayerSessionC2SPacket.java:27) ~[server-intermediary.jar:?]
        at MC/net.minecraft.network.packet.c2s.play.PlayerSessionC2SPacket.apply(PlayerSessionC2SPacket.java:9) ~[server-intermediary.jar:?]
        at MC/net.minecraft.network.NetworkThreadUtils.method_11072(NetworkThreadUtils.java:27) ~[server-intermediary.jar:?]
        at MC/net.minecraft.server.ServerTask.run(ServerTask.java:18) ~[server-intermediary.jar:?]
        at MC/net.minecraft.util.thread.ThreadExecutor.executeTask(ThreadExecutor.java:162) ~[server-intermediary.jar:?]
        at MC/net.minecraft.util.thread.ReentrantThreadExecutor.executeTask(ReentrantThreadExecutor.java:23) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:864) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:173) ~[server-intermediary.jar:?]
        at MC/net.minecraft.util.thread.ThreadExecutor.runTask(ThreadExecutor.java:136) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.runOneTask(MinecraftServer.java:846) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.runTask(MinecraftServer.java:840) ~[server-intermediary.jar:?]
        at MC/net.minecraft.util.thread.ThreadExecutor.runTasks(ThreadExecutor.java:121) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.runTasksTillTickEnd(MinecraftServer.java:814) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:702) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:281) ~[server-intermediary.jar:?]
        at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
[11:18:39] [Server thread/ERROR]: Failed to verify Services signature
java.security.SignatureException: Bad signature length: got 1 but was expecting 512
        at java.base/sun.security.rsa.RSASignature.engineVerify(RSASignature.java:212) ~[?:?]
        at java.base/java.security.Signature$Delegate.engineVerify(Signature.java:1422) ~[?:?]
        at java.base/java.security.Signature.verify(Signature.java:790) ~[?:?]
        at MC/net.minecraft.network.encryption.SignatureVerifier.verify(SignatureVerifier.java:28) ~[server-intermediary.jar:?]
        at MC/net.minecraft.network.encryption.SignatureVerifier.method_44173(SignatureVerifier.java:53) ~[server-intermediary.jar:?]
        at java.base/java.util.stream.MatchOps$1MatchSink.accept(MatchOps.java:90) ~[?:?]
        at java.base/java.util.AbstractList$RandomAccessSpliterator.tryAdvance(AbstractList.java:708) ~[?:?]
        at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129) ~[?:?]
        at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:527) ~[?:?]
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:513) ~[?:?]
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
        at java.base/java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230) ~[?:?]
        at java.base/java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:196) ~[?:?]
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
        at java.base/java.util.stream.ReferencePipeline.anyMatch(ReferencePipeline.java:632) ~[?:?]
        at MC/net.minecraft.network.encryption.SignatureVerifier.method_51496(SignatureVerifier.java:50) ~[server-intermediary.jar:?]
        at MC/net.minecraft.network.encryption.SignatureVerifier.validate(SignatureVerifier.java:23) ~[server-intermediary.jar:?]
        at MC/net.minecraft.network.encryption.PlayerPublicKey$PublicKeyData.verifyKey(PlayerPublicKey.java:74) ~[server-intermediary.jar:?]
        at MC/net.minecraft.network.encryption.PlayerPublicKey.verifyAndDecode(PlayerPublicKey.java:30) ~[server-intermediary.jar:?]
        at MC/net.minecraft.network.encryption.PublicPlayerSession$Serialized.toSession(PublicPlayerSession.java:42) ~[server-intermediary.jar:?]
        at MC/net.minecraft.server.network.ServerPlayNetworkHandler.onPlayerSession(ServerPlayNetworkHandler.java:1889) ~[server-intermediary.jar:?]
        at MC/net.minecraft.network.packet.c2s.play.PlayerSessionC2SPacket.apply(PlayerSessionC2SPacket.java:27) ~[server-intermediary.jar:?]
        at MC/net.minecraft.network.packet.c2s.play.PlayerSessionC2SPacket.apply(PlayerSessionC2SPacket.java:9) ~[server-intermediary.jar:?]
        at MC/net.minecraft.network.NetworkThreadUtils.method_11072(NetworkThreadUtils.java:27) ~[server-intermediary.jar:?]
        at MC/net.minecraft.server.ServerTask.run(ServerTask.java:18) ~[server-intermediary.jar:?]
        at MC/net.minecraft.util.thread.ThreadExecutor.executeTask(ThreadExecutor.java:162) ~[server-intermediary.jar:?]
        at MC/net.minecraft.util.thread.ReentrantThreadExecutor.executeTask(ReentrantThreadExecutor.java:23) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:864) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:173) ~[server-intermediary.jar:?]
        at MC/net.minecraft.util.thread.ThreadExecutor.runTask(ThreadExecutor.java:136) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.runOneTask(MinecraftServer.java:846) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.runTask(MinecraftServer.java:840) ~[server-intermediary.jar:?]
        at MC/net.minecraft.util.thread.ThreadExecutor.runTasks(ThreadExecutor.java:121) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.runTasksTillTickEnd(MinecraftServer.java:814) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:702) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:281) ~[server-intermediary.jar:?]
        at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
[11:18:39] [Server thread/ERROR]: Failed to validate profile key: Invalid signature for profile public key.
Try restarting your game.
[11:18:39] [Server thread/INFO]: sqsqd118 lost connection: Invalid signature for profile public key.
Try restarting your game.

**Comment by FIGRJA** [comment]
I have already seen a similar error with my mod somewhere and have encountered it myself, but for some reason the solution to this problem is to reinstall the client version.

**Comment by alexsovi** [comment]
It somehow worked on Legacy Launcher.
Thanks.
